# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.wagtailroutablepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('cs_core', '0011_auto_20160706_1149'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('cs_questions', '0009_quizresponseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='quizlist',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='QuestionList',
        ),
        migrations.DeleteModel(
            name='QuizList',
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=(wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin, 'cs_core.rootlist'),
        ),
        migrations.CreateModel(
            name='QuizList',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cs_core.rootlist',),
        ),
    ]
