# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('length', 'length'), ('time', 'time')], default='length', help_text='Choose a battle type.', max_length=20, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='BattleResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='cs_battles.Battle')),
            ],
        ),
    ]
